name: workflow to count words
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo 'hello world'
        shell: bash
        
  check_if_markdown_used:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9


      - name: word counts in markdown cells
        run: |
          python tests/wc.py
