name: workflow to count words
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo 'hello world'
        shell: bash
        
  check_if_markdown_used:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install python packages
        run: |  #  python -m pip install --upgrade pip
          pip install -r pack.yml
      - name: run the wc.py script that counts words in markdown cells
        run: |
          python tests/wc.py
